-- ============================================
-- 1. Creación de la tabla PROFESORES
-- ============================================
CREATE TABLE IF NOT EXISTS PROFESORES (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    juego VARCHAR(180) NOT NULL
);

-- ============================================
-- 2. Creación de la tabla ALUMNOS (CON fecha_creacion)
-- ============================================
CREATE TABLE IF NOT EXISTS ALUMNOS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    edad INT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,  -- ← AÑADIDO
    profesor_id BIGINT,
    FOREIGN KEY (profesor_id) REFERENCES PROFESORES(id)
);

-- ============================================
-- 3. Secuencias (opcionales)
-- ============================================
DROP SEQUENCE IF EXISTS PROFESORES_SEQ;
CREATE SEQUENCE IF NOT EXISTS PROFESORES_SEQ START WITH 100 INCREMENT BY 1;

DROP SEQUENCE IF EXISTS ALUMNOS_SEQ;
CREATE SEQUENCE IF NOT EXISTS ALUMNOS_SEQ START WITH 100 INCREMENT BY 1;