-- ============================================
-- 1. Creación de la tabla PROFESORES (antes CATEGORIAS)
-- ============================================
CREATE TABLE IF NOT EXISTS PROFESORES (
    id BIGINT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- ============================================
-- 2. Creación de la tabla ALUMNOS (antes PRODUCTOS)
-- ============================================
CREATE TABLE IF NOT EXISTS ALUMNOS (
    -- Clave Primaria autogenerada
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    nombre VARCHAR(255) NOT NULL,
    edad INT NOT NULL,                     -- Nueva columna (antes precio, peso, etc.)
    fecha_creacion TIMESTAMP NOT NULL,
    
    -- Clave Ajena hacia PROFESORES
    profesor_id BIGINT,
    FOREIGN KEY (profesor_id) REFERENCES PROFESORES(id)
);

-- ============================================
-- 3. Secuencias para IDs automáticos (opcional pero recomendado)
-- ============================================
DROP SEQUENCE IF EXISTS PROFESORES_SEQ;
CREATE SEQUENCE IF NOT EXISTS PROFESORES_SEQ START WITH 100 INCREMENT BY 1;

DROP SEQUENCE IF EXISTS ALUMNOS_SEQ;
CREATE SEQUENCE IF NOT EXISTS ALUMNOS_SEQ START WITH 100 INCREMENT BY 1;